### ISSUE TITLE
Support for Z Scatter module

### ISSUE THREAD

**Issue by King-Wedgie** [mclemente/healthEstimate#156] opened 2023-04-15 23:38 UTC
https://foundryvtt.com/packages/z-scatter

Z Scatter spreads out tokens that share a space so that they're easier to manage (useful for party movement or when a player is sharing a space with a Hazard in PF2E). Health estimate text currently doesn't follow their respective tokens:
![image](https://user-images.githubusercontent.com/73143074/232258493-a934fc4e-8806-453a-9aca-80fbbfd36fc8.png)

**Comment by mclemente** [comment] 2023-04-16 02:18
That's a really creative module.

The issue is that the estimate's position takes just the (token's size X token's width) and doesn't take into account it's image. The same happens when opening the Token HUD.

I'll see what I can do.

**Comment by mclemente** [comment] 2023-04-16 22:21
Should be fixed now.
The only issue being that the Always Show Estimates setting will render the estimates wrong when loading a scene. And that can't really be fixed since neither me or Z Scatter's author can set which hook will be called first.

**Closed by mclemente** 2023-04-16 22:21 UTC
Labels: enhancement
