### ISSUE TITLE
Document Class and Data Model Error

### ISSUE THREAD

**Issue by RinVindor** [mclemente/healthEstimate#191] opened 2023-08-01 02:41 UTC
**Describe the bug**
Happens when hovering cursor over the tokens (they do display their health estimate correctly). Thanks for the hard work on this mod, its one of my must haves.

**Screenshots**
![image](https://github.com/mclemente/healthEstimate/assets/12647469/fc2f6d23-b126-475a-bb77-97fc432dae50)

**Game Specifics (please complete the following information):**
 - Foundry V11
 - Chronicles of Darkness 2E version 0.12.2
 - Health Estimate version 31.2

**Comment by mclemente** [comment] 2023-08-01 05:43
This is caused by your `Hit Points Attribute Data Path` setting being set to something like `actor.data.data...`. Just replace `data.data` for `system` and it'll be fixed.

There is nothing I can do to fix this, so I will be closing this as a "won't fix".

**Closed by mclemente** 2023-08-01 05:43 UTC
Labels: bug
