### ISSUE TITLE
Health Estimate position changes if token elevation is greater than 0

### ISSUE THREAD

**Issue by weepingminotaur** [mclemente/healthEstimate#82] opened 2022-06-22 03:32 UTC
I have the Health Estimate display set to Middle. However, whenever I increase the elevation of a token to a number greater than 0, the Health Estimate display text jumps up so that it overlaps with the elevation display on top of the token. Reloading Foundry or moving to another map and back fixes the issue, but it is still a problem that affects any tokens with elevation.

**Comment by mclemente** [comment] 2022-06-22 04:06
I need more info, I couldn't reproduce this, the text kept at the middle when I changed the token's elevation.

**Comment by weepingminotaur** [comment] 2022-06-23 01:12
Well, I just spent a chunk of time running Find the Culprit to figure out if there was a module incompatibility, and now I can't reproduce the bug! :) Sorry about that. If it crops up again, I will let you know and provide all the info I have.

**Comment by mclemente** [comment] 2022-09-09 00:46
Closing since the problem doesn't seem to have happened again since June.

**Closed by mclemente** 2022-09-09 00:46 UTC
